CREATE SEQUENCE IF NOT EXISTS pole_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS region_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS substation_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS transformer_seq START WITH 1 INCREMENT BY 1;
